### ISSUE TITLE
Unable to load PlatformApi from platform. SyntaxError: Unexpected token 

### ISSUE THREAD

**Issue by alemdg** [apache/cordova-ios#1000]
Hello, using ionic

ionic cordova platforms add ios@6.1.0 
Unable to load PlatformApi from platform. SyntaxError: Unexpected token ...
Uncaught, unspecified "error" event. (The platform "ios" does not appear to be a valid cordova platform. It is missing API.js. ios not supported.)

regards.

**Comment by breautek** [comment]
You're using a dated version of NodeJS.

Recommended version is Node 12, but minimum is 10.

We only support the latest minor/patch releases of a given major. Currently at the time of writing, this means you should have either:
- Node 10.22.1
- Node 12.18.4

If you need further support, please ask our [slack](http://slack.cordova.io/). If you think you've found a bug with Cordova, then please open a new issue with the issue form **filled** out (rather than deleting it). Thank you.
