### ISSUE TITLE
a few seconds of blank screen when starting the app

### ISSUE THREAD

**Issue by lynntangyuan** [apache/cordova-ios#1010]
# Bug Report

## Problem
Each time I restart my application, There are a few seconds of blank screen. After that, Page can be loaded normally. How can I make the blank screen disappear?

### What is expected to happen?

No blank screen while launching my application.

### What does actually happen?

There are a few seconds of blank screen when starting the app

### Command or Code

<preference name="FadeSplashScreen" value="true" />
<preference name="FadeSplashScreenDuration" value=".25" />
<preference name="ShowSplashScreenSpinner" value="true" />
<preference name="AutoHideSplashScreen" value="true" />
<preference name="SplashScreenDelay" value="3000" />

### Environment, Platform, Device

- Cordova-ios6.1.0

- Xcode 12.0

- MacOS Catalina10.15.6

- iOS14.0

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by adeelcap15** [comment]
Are you using Splash screen properly?

**Comment by lynntangyuan** [comment]
> Are you using Splash screen properly?

@adeelcap15 As far as I'm concerned, Cordova6.1.0 has cancelled CDVSplashScreen, In file "CDVViewController.m", it launched The LaunchView by itself. I tried to block the code: [self createLaunchView];  the display time of blank screen reduced to 1 second

**Comment by adeelcap15** [comment]
IMHO you should use the newer CDVLaunchScreen. It's working fine on Cordova IOS 6.1.1 on iOS 14

**Comment by asa47** [comment]
@lynntangyuan Did you manage to solve the issue?
We are having the same issue, but I cant figure out what is triggering the white screen.

@adeelcap15 Does the CDVLaunchScreen support the legacy splash screen? If possible we would rather not use the story board in order to keep the same resolution when running the app on the iPad Pro ([iPad Pro scale issue](https://developer.apple.com/forums/thread/36336)).

**Comment by breautek** [comment]
> Does the CDVLaunchScreen support the legacy splash screen? If possible we would rather not use the story board in order to keep the same resolution when running the app on the iPad Pro (iPad Pro scale issue).

Support for legacy launch screens was removed in 6.0.0 via https://github.com/apache/cordova-ios/pull/790

I think the main reason for this is Apple will reject any apps still using legacy splash screens, as of April 2020.

**Comment by lynntangyuan** [comment]
> IMHO you should use the newer CDVLaunchScreen. It's working fine on Cordova IOS 6.1.1 on iOS 14
@adeelcap15 The launch Screen can be loaded normally. After that, when app tried to load CDVViewController based on WKWebview, the blank screen appeared.
@asa47 are U under the same circumstances as I described above? Sorry to info that I haven't solve this issue yet.

**Comment by asa47** [comment]
@lynntangyuan Yes I sorted the issue on our side, however I am still using the legacy launch screen.

Regarding the white screen, it looks like it is caused by the JS code not being loaded quickly enough in the WebView after displaying the splash/launch screen. In order to fix the issue, I manually hide the splash screen in the javascript side with `navigator.splashscreen.hide()`.
Just remember to add the following in your config.xml: `<preference name="AutoHideSplashScreen" value="false" />`

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been over a year with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
