### ISSUE TITLE
Opening Websql Database on IOS

### ISSUE THREAD

**Issue by Magu0013** [apache/cordova-ios#1043]
I took over an Cordova cross platform app that still uses websql and need it to switch to the sqllite plugin. I had no problem doing this with android, but im stuck with the IOS version.

My main problem is, that I need to acces the Websql database one last time to copy the data to the new sqllite DB. On Android everything works, but no matter what I do on IOS, it says that websql ist deprecated. I know its deprecated but the customers still have data on the old Database, and the App in the store still uses websql. To move to a new standard I need to acces the Websql DB one last time to transfer the data.

Also the app thats aleready published in the store works without any problems, so websql still works ther. 

What can I do to save the Data inside the old websql DB?

**Comment by NiklasMerz** [comment]
As far as I understand this is not a Cordova issue in particular. WebSQL is part of the webviews API (UIWebView or WKWebView). I suggest you to search stackoverflow etc. for WebSQL in WKWebView or UIWebView on iOS. You may be lucky there.

**Comment by Magu0013** [comment]
Yeah the problem is I already tried this. I asked on Stackoverflow and only found someone with same problem but no solution. I also asked directly in the apple developer forums and also got no response. It seems like no one has a clue about this.

**Comment by breautek** [comment]
Migrating data is going to be impossible without some plugin with some native code. Even then I'm not sure if is possible migrating WebSQL.

There is a plugin that we used to migrate WKWebView local storage (with file:// based origin) to WKWebView using schemes (in this case... ionic:// scheme). I would _expect_ the WebSQL physical files to be located along side of the `LocalStorage` directory or something, so that's where I'll be prodding around. I think you can use xcode to browse through the app's private data.

https://github.com/totalpave/cordova-plugin-migrate-localstorage/blob/master/src/ios/MigrateLocalStorage.m
