### ISSUE TITLE
Swipe Back stopped working after migrating from cordova-ios 5.1.1 to cordova-ios 6.1.1

### ISSUE THREAD

**Issue by parvageshahariar** [apache/cordova-ios#1064]
# Bug Report

## Problem
Swipe Back Not Working after upgrading to Cordova-ios 5.1.1 to 6.1.1

### What is expected to happen?
sdds

### What does actually happen?
Swipe back is working for Ionic v1 and Cordova-ios 5.1.1. But When I upgrade to newer version of cordova-ios, swipe back stopped working.

## Information

This is 100% replicable as I get every pages where I enable swipe back.

### Command or Code

$ionicConfig.views.swipeBackEnabled(true); 
not working alongside  can-swipe-back="true"  

<ion-view title="" cache-view="false" can-swipe-back="true">

### Environment, Platform, Device

Experiencing this issue in Ipad & Iphone (ios version 13,14)

### Version information
Cordova version: 10.0,1
Cordova-Ios version: 6.1.1
ionic version: v1
Xcode: 11.2.1

## Checklist

- [x ] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by breautek** [comment]
There is a `WkWebView.allowsBackForwardNavigationGestures(true)` api available (from JS) to enable navigation gestures.

Testing this with a vanilla cordova application and this works, so I'll be closing this ticket. You can try using this API instead of `$ionicConfig.views.swipeBackEnabled(true);`. If for some reason you cannot use the cordova API directly, you'll need to raise this concern with Ionic.
