### ISSUE TITLE
OTP code is not inserted into input

### ISSUE THREAD

**Issue by spargo-protek** [apache/cordova-ios#1075]
# Bug Report
When sms with OTP code arrives it is shown on the top of keyboard, but clicking it doesn't do anything.

### What is expected to happen?
Clicking the code should insert it in the focused input.

### What does actually happen?
Clicking the code does nothing.

## Information

By the way the way code is displayed in safari and cordova differs:
![Skype_Picture_2021_02_16T00_02_24_129Z](https://user-images.githubusercontent.com/55238788/108003971-78df9c80-7005-11eb-85b8-6becb7aaf8da.jpeg)

![Skype_Picture_2021_02_16T00_02_33_887Z](https://user-images.githubusercontent.com/55238788/108003973-7a10c980-7005-11eb-8ad4-ca69fd965eaa.jpeg)

### Code
Create new cordova project:
cordova create hello com.example.hello HelloWorld

Edit index.html adding:
`<input id="single-factor-code-text-field" type="text" autocomplete="one-time-code"/>`
after:
`<p class="event received">Device is Ready</p>`

Request sms by any site that requires sms validation.
Click the edit.
See code in keyboard.
Click the code.

### Environment, Platform, Device

iPhone 6s, ios 14.4.

### Version information

cordova 10.0
cordova-ios 6.1.1

## Checklist

- [x ] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been over a year with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

However, I think the OTP completion on iOS relies on some association between the code and the domain of the web content, and probably isn't supported in WKWebView.

**Comment by dpogue** [comment]
Closing as stale.
