### ISSUE TITLE
IOS not using display-mode: standalone

### ISSUE THREAD

**Issue by nesbtesh** [apache/cordova-ios#1085]
**Describe the bug**
When i generated my iOS app I noticed that is not using the display-mode: standalone feature in iOS

It works perfect in android but not in iOS

**URL to app**
https://www.noritex.com/es/

**Expected behavior**
I expect the layout to change using the standalone display-mode

**Screenshots**
Result:  
<img width="367" alt="Screen Shot 2021-02-24 at 5 56 39 PM" src="https://user-images.githubusercontent.com/3814044/109077110-a5f91280-76c9-11eb-93be-6cc2f6e9540f.png">

Expected: 

<img width="385" alt="Screen Shot 2021-02-24 at 5 57 36 PM" src="https://user-images.githubusercontent.com/3814044/109077209-ca54ef00-76c9-11eb-8827-79bb2f584cbd.png">

**Additional info (please complete the following information):**
 - OS: iOS

**Comment by nesbtesh** [comment]
Is there any to force use display-mode in stadalone

**Comment by breautek** [comment]
I'm not really sure if I'm understanding your issue correctly. You don't need to force the webview to do anything, you just simply need to use the CSS.

Cordova doesn't force specific settings that is controllable by CSS because obviously that will take away control from the app developer.

So how are you setting the `display-mode` css rule?

I'm not sure what the pixel resolution value of iOS devices on top of my head, but is it possible that it doesn't fit the media query `@media (max-width: 550px) and (display-mode:standalone)`?

**Comment by dpogue** [comment]
As far as I know, there's no way for an app (or Cordova for that matter) to force WebKit to set the `display-mode` for CSS media queries 😞

**Comment by nesbtesh** [comment]
Is there a way at least to remove the empty space below and above the app

<img width="458" alt="Screen Shot 2021-02-25 at 10 02 52 AM" src="https://user-images.githubusercontent.com/3814044/109175245-9de5b500-7753-11eb-8ab7-f4fac03a07fc.png">

**Comment by nesbtesh** [comment]
@breautek @dpogue let me know what you think

**Comment by breautek** [comment]
The spacing is safe area insets. Apple has a webkit blog that explains how to manipulate your content around safe areas:

https://webkit.org/blog/7929/designing-websites-for-iphone-x/
