### ISSUE TITLE
Release including Swift Package Manager support

### ISSUE THREAD

**Issue by zettlunic** [apache/cordova-ios#1267]
Hey folks! Wanted to check if there's any plan to create a tag/release including the Package.swift file which is necessary for SPM support?

We currently pin against 480a3c26bdd02e1a97844467e79bfa5a49ae5800, which works just fine. An explicit tag would feel nicer though.

Is there anything we can do to help?

TIA!

**Comment by apps4everyone** [comment]
Any news here? Master has SPM Support but no tag / release so far 😢

**Comment by dpogue** [comment]
To be clear, the support on the master branch for SPM only supports **installing** CordovaLib as a Swift package. It does not (yet) support plugins adding dependencies using SPM (See https://github.com/apache/cordova-ios/issues/1089 for that).

There was some restructuring to the CordovaLib project as part of that work and removal of deprecated APIs, so that won't be released until the next major version (7.0.0) which has some other outstanding work to be done first.

**Comment by apps4everyone** [comment]
thx @dpogue for the clarification, and the work 👍🏼

**Comment by andrerds** [comment]
Oops! Wonderful work by you, congratulations.

Friends, what is the other way to add a swift package in custom plugins?

I'm trying to make a custom plugin that works to lock the printscreen screenshot. Because what exists at the moment does not block the screenshot.
I found this package > https://github.com/Stampoo/SnapshotSafeView

seems to be very promising, in native it works beautifully.

Could you guide me how should I do it or if it is possible to use another way to import the package?

**Comment by dpogue** [comment]
Going to close this issue. Support for consuming CordovaLib as a Swift package was added in version 7.0.0.

Support for plugins using Swift packages is an open issue being tracked in #1089.
