### ISSUE TITLE
Blank gray splash screen on iOS 16

### ISSUE THREAD

**Issue by loozmax** [apache/cordova-ios#1287]
# Bug Report

## Problem

When you open the application, instead of a splash screen, a blank gray screen appears.

### What is expected to happen?

I'm waiting to see the image

### What does actually happen?

Blank gray screen

## Information
As a possible solution, I saw that you can roll back the plugin version to 5.0.0 and it really helped, but on iOS 16 the problem reappeared.

### Environment, Platform, Device
iOS 16

### Version information
cordova-ios: "^5.1.1"
cordova-plugin-splashscreen: "5.0.0"

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
> As a possible solution, I saw that you can roll back the plugin version to 5.0.0 and it really helped,

Rollback to 5.0.0 from what version?

If version 6 causes this problem that would be because version 6.x drops iOS code, because cordova-ios@6 implements splash screens in the core platform, making the plugin obsolete. But I see you're still on cordova-ios@5 which will require cordova-plugin-splashscreen@5 for splashscreens.

**Comment by loozmax** [comment]
> > As a possible solution, I saw that you can roll back the plugin version to 5.0.0 and it really helped,
> 
> Rollback to 5.0.0 from what version?
> 
> If version 6 causes this problem that would be because version 6.x drops iOS code, because cordova-ios@6 implements splash screens in the core platform, making the plugin obsolete. But I see you're still on cordova-ios@5 which will require cordova-plugin-splashscreen@5 for splashscreens.

Previously was version 6.0.2

**Comment by breautek** [comment]
Thanks for your swift response.

In this case, the behaviour would be intentional. Version 6 has **no** iOS implementatoin for splashscreens, and neither does cordova-ios@5.

So if you plan on staying on cordova-ios@5 then you'll need to continue to use cordova-plugin-splashscreen@5. When you upgrade to cordova-ios@6, the cordova-plugin-splashscreen is no longer relevant for iOS. If you use the browser platform or android@10 and earlier, then you can keep the splashscreen plugin installed for those platforms. Otherwise the plugin is completely obsolete and can be uninstalled.

Closing as not-a-bug.
