### ISSUE TITLE
default ios schema changed

### ISSUE THREAD

**Issue by profenpoche** [apache/cordova-ios#1294]
Hello,

Today our app didn't load when building on ios device. 

Looking into dev console, the main files (cordova.js, etc...) didn't load because of url file://cordova.js.
Adding scheme and protocol in config.xml to come back to previous values (ionic://localhost/) solved our problem.

Is there any reason to this change ?
Did we miss something ? 

Thanks in advance

**Comment by breautek** [comment]
cordova-ios default is to use the file scheme.

cordova-ios will enabled schemes if the following preferences are present
```
<preference name="scheme" value="app" />
<preference name="hostname" value="localhost" />
```

If `scheme` is an illegal value, it will fallback to `app`.

None of this applies if you're using a webview plugin like `cordova-plugin-ionic-webview` since it takes responsibility of managing the webview settings.

Cordova has never defaulted to `ionic://localhost` scheme, but it was the ionic's webview default.

Closing as this doesn't appear to describe a bug with cordova-ios.

**Comment by profenpoche** [comment]
Thanks for the explanation ! 

I will look into ionic webview for changes explaining this scheme change.
