### ISSUE TITLE
WKWebView no longer debuggable on iOS 16.4+

### ISSUE THREAD

**Issue by daviesdoclc** [apache/cordova-ios#1321]
# Bug Report

## Problem

The WKWebView is no longer debuggable on iOS 16.4+ even with the fix in cordova-ios 6.3.0 (https://github.com/apache/cordova-ios/pull/1300).

### What is expected to happen?

I should be able to connect to the WKWebView via Desktop Safari when building my app in debug mode.

### What does actually happen?

The WKWebView does not show up in the Developer Tools under my device.  My Capacitor app in the same environment is debuggable.

## Information

Running ```cordova run ios --device --debug```

Tried adding ```<preference name="InspectableWebview" value="true"/>``` to config.xml and still no luck.

I am using the standard WKWebView.

### Command or Code

See above

### Environment, Platform, Device

cordova-ios

### Version information

iOS 16.4.1, MacOS 13.3.1, Safari 16.4, cordova-ios 6.3.0, cordova 11.1.0

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by daviesdoclc** [comment]
My bad.  This was me overwriting the WKWebView during install via a hook. Sorry.

**Comment by Kashaf14** [comment]
@daviesdoclc  i am still unable to get this working , would you please explain what was your mistake? 

It would be great.

**Comment by dpogue** [comment]
@Kashaf14 This has been fixed in cordova-ios 6.3.0 for the built-in Cordova webview.

If you are using the cordova-plugin-ionic-webview plugin rather than the built-in webview, then support for the web inspector needs to be added by the Ionic team that maintains that plugin. You can report bugs on their plugin repo here: https://github.com/ionic-team/cordova-plugin-ionic-webview
