### ISSUE TITLE
Cordova-ios@6.3.0 fails on Running command: xcrun simctl list --json

### ISSUE THREAD

**Issue by BartolomeoItaliano** [apache/cordova-ios#1366]
Cordova-ios listing command fails occasionally.
After couple of reruns I am sometimes able to make the command finally pass.
However, the command fails on external GitLab pipelines runners and I cannot afford to have it left without a solution.

Stack trace before the fail:

```
cordova build ios --release
List simulator targets
Running command: xcrun simctl list --json
Select last emulator from list as default.
List simulator targets
Running command: xcrun simctl list --json
Cannot read properties of undefined (reading 'name')
[ERROR] An error occurred while running subprocess cordova.
        
        cordova build ios --release exited with exit code 1.

```        

Environment:
External Gitlab iOS runner
Mac OS 12
xCode 14

Cordova-iOS version:
6.3.0

Cordova version:
11.0.0

**Comment by alexandreperron** [comment]
The reason for this is that no ios simulator is downloaded in xcode.

**Comment by alitalaee** [comment]
I had the same issue when because of Low space on my mac decided to remove some IOS Simulators. i removed some Simulators from **~/Library/Developer/Xcode/iOS DeviceSupport/** and then when try to build ios app it gives me the same error

Solution 
`sudo ionic cordova build ios --prod`
This will work
