### ISSUE TITLE
SplashScreen not loading on cordova-ios@7.0.1

### ISSUE THREAD

**Issue by adirgan** [apache/cordova-ios#1401]
# Bug Report

## Problem

When I just prepared for iOS, everything is created correctly, and I manage to run the application in the iOS emulator, but the splash screen does not load, it remains blank

### What is expected to happen?

When adding the iOS platform, the splash screen is created correctly and displayed when the app is run

### What does actually happen?

When I prepared the app for iOS, everything was created correctly and I managed to run the app in the iOS emulator, but the home screen does not load, it remains blank.

Now when I try to manually place the Launch Screen File in General, and place the CDVLaunchScreen.storyboard and compile, the app no longer loads, every time I open the app it crashes with the following error.

"*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Could not find a storyboard named 'CDVLaunchScreen.storyboard' in bundle NSBundle"

I tried to create a Launch.storyboard myself in xcode, and it always gives me the same error that it cannot be found in the NSBundle.

I've been trying to figure out a solution for 10 hours, and I can't find any solution.

## Information

Add iOS to a Cordova project in version 7.0.1, and prepare the project

### Environment, Platform, Device

Mac OS, Sonoma

Emulator of iOS 17.2

### Version information

Cordova CLI: 12.0.0
Cordova IOS: 7.0.1

Mac OS Sonoma, Xcode 15.2

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
can you provide a sample app?

**Comment by adirgan** [comment]
Any idea what it could be?

@jcesarmobile @taxman007

**Comment by adirgan** [comment]
Could you give me a clearer idea of how you solved it?

Since I installed everything fresh, but it only happens when I upgrade to version 7

When you refer to adding the splash screen manually, what do you mean?


Sorry for the inconvenience, I've really been dealing with this for a long time and I need to solve it.

@taxman007 Thanks if you can help me

**Comment by matictrebusak** [comment]
I experienced this issue as well. I was getting two different splashes, first is native ios and then cordova splash, which did not scale and was shown as logo being off-center. Solution for me was:

1. (may be optional) Add "Default@3x~universal~anyany.png" (2208x2208) as well to config.xml and resource folder. This asset should be smaller then @2x as referenced in cordova docs. If it uses 2x (2732X2732), which worked ok in cordova-ios@6+, it is actually too big , and you experience first black screen and then white screen because splash screen is not appropriately read.  So my config for ios splash is: 
`<splash src="resources/ios/splash/Default@2x~universal~anyany.png"/>
<splash src="resources/ios/splash/Default@3x~universal~anyany.png"/>`
2. (needed) I found a fork in which a feature for rotating splash screens is reverted (was introduced in 7.0.0 I think) https://github.com/jessyefuster/cordova-ios/commits/7.1.1

I imagine this will be merged soon to main project and everything will be well again. Hope it helps someone in the meanwhile as I was stuck with this for one week.

**Comment by GitToTheHub** [comment]
@matictrebusak You wrote:
> which did not scale and was shown as logo being off-center.
I hade a similar issue. First the splashscreen was showed correctly and switched off-centered at the end. The issue was caused by the plugin cordova-plugin-googlemaps. After removing the plugin, the splashscreen was shown correctly durring the load time.

**Comment by ngoquoc** [comment]
@GitToTheHub I had the same issue, tried removing cordova-plugin-googlemaps and the problem disappeared. Have you maybe figured out what chunk of code in cordova-plugin-googlemaps that causes the issue? Thanks!

**Comment by GitToTheHub** [comment]
@ngoquoc No, I didn’t figure out, which part of the plugin causing the issue:/

**Comment by GitToTheHub** [comment]
Ok good to know

**Comment by maniya108** [comment]
Hi, Our team also facing the same problem in cordova-ios: 7.1.1. Please provide the workaround to overcome this issue. Thanks in advance!!!

**Comment by sajid-robo** [comment]
Hi,
We are encountering the same issue on iOS where the splash screen is replaced by a black screen before loading the main screen of the app. Any insights or solutions would be greatly appreciated. Thank you!

**Comment by jcesarmobile** [comment]
black screen is caused by too big images, since iOS 14 devices don't seem to handle images of more than 100kb and bigger than 2400x2400px.

**Comment by maniya108** [comment]
@jcesarmobile our universal image size is 151kb and 2732*2732px, due do that its not working. Do i need to change the size and dimensions?.

**Comment by maniya108** [comment]
Hi Team, Someone marked my comment as abuse. I dont know why. Getting splashscreen black and white issue after updated the latest cordova-ios 7.1.1.  Please provide the workaround to overcome this issue. Thanks in advance!!!

**Comment by GitToTheHub** [comment]
Remove and add the ios platform again. Look in XCode, if you can see the associated splashscreens. Do you use png format for the splashscreen?

**Comment by GitToTheHub** [comment]
You don't have to set `height` and `width`, just add:

`<splash src="resources/ios/splash/Default@2x~universal~anyany.png" />`

**Comment by maniya108** [comment]
Ok, Let me try

**Comment by iPMisterX** [comment]
> @matictrebusak You wrote:
> 
> > which did not scale and was shown as logo being off-center.
> 
> I hade a similar issue. First the splashscreen was showed correctly and switched off-centered at the end. The issue was caused by the plugin cordova-plugin-googlemaps. After removing the plugin, the splashscreen was shown correctly durring the load time.

same i dont know how to fix this i need to use cordova-plugin-googlemaps :(

**Comment by GitToTheHub** [comment]
@iPMisterX I made a PR to fix this https://github.com/mapsplugin/cordova-plugin-googlemaps/pull/2936

**Comment by outofcontrolmike** [comment]
@GitToTheHub 

I also experience the issue with the different splash screens, as in the second one being off centered.  It's very interesting that I finally found some thread where people were having a similar problem.  I look forward to your PR being merged and seeing if the issue fixed in my testing.  Thank you.

**Comment by outofcontrolmike** [comment]
The above PR did resolve my issue for me in my testing.

**Comment by GitToTheHub** [comment]
@outofcontrolmike I am pleased :)

**Comment by adirgan** [comment]
Thanks @GitToTheHub, With your PR the problem was solved

**Comment by GitToTheHub** [comment]
I'm happy I could help :)
