### ISSUE TITLE
Copy deployment-target from root config.xml to platform-specific config.xml before usage in Podfile

### ISSUE THREAD

**Issue by expcapitaldev** [apache/cordova-ios#1422]
**Issue**
Currently, the deployment-target variable is not being copied from the root config.xml file to the platforms/ios/[App Name]/config.xml before it is accessed in the code. As a result, the script uses the default deployment target from the template (https://github.com/apache/cordova-ios/blob/rel/7.0.1/templates/project/__PROJECT_NAME__/config.xml) instead of the user-specified value in the root config.xml.
It is mean in Podfile we will have deployment-target from root config.xml only first successful prepare hook.
Reproduce is very easy: try to install any pod library with ios target version more than 11. -> you will have error

**Expected Behavior**
The deployment-target set in the root config.xml should be reflected in the platforms/ios/[App Name]/config.xml before any script or process accesses it.

**Proposed Solution**
Modify the lib/prepare.js file to ensure that deployment-target and possibly other preferences are copied from the root config.xml to the platforms/ios/[App Name]/config.xml early in the preparation process. This could potentially be implemented at line 250, before the preferences are required by subsequent processes in the script.

**Additional Information**
This change will ensure that the deployment target and other settings are correctly set according to the project's configuration before they are needed, preventing any default settings from causing conflicts or errors during build or runtime.

**Workaround:**
- do form from cordova-ios library or do any postinstall here: https://github.com/apache/cordova-ios/blob/master/lib/Podfile.js#L40. to `this.minDeploymentTarget = minDeploymentTarget || '13.0';`

**Comment by breautek** [comment]
This was an issue in cordova-ios 6.3 but I believe was patched in 7.0 (definitely in 7.1).

I have a google maps plugin that requires iOS 15 and I used to manually workaround this issue but it was corrected after I updated my projects to 7.1.

I used:

```xml
<platform name="ios">
  <preference name="deployment-target" value="15.0" />
</platform>
```

adding the plugin and then the platform works as expected, with the generated podfile properly containing `15.0` instead of the default `11.0`. This also works if you add the platform first, or use the preference outside of the `<platform name="ios">` block. Updating the preference and running `cordova prepare ios` also shows the changes reflected in both the platform's `Podfile` and `config.xml`.

> The deployment-target set in the root config.xml should be reflected in the platforms/ios/[App Name]/config.xml before any script or process accesses it.

The expectation of "any script or process" is not quite right. The platform files (including config.xml and Podfile) gets updated during the `prepare` step, so if you're using an hook, script or process that runs before prepare (such as `before_prepare` hook) for example, that will run before the config.xml file is updated inside the platform project, and that would be desired behaviour because the hook is for manipulating things before cordova does things. `after_prepare` is a hook for after cordova manipulates things, etc.

I can not reproduce the issue using the current version of cordova-ios. Simply adding a plugin in which requires a higher deployment target of 11 is not enough to reproduce the issue. If you can provide a sample reproduction project, it may help us understanding the full scope of when the issue reproduces.

**Comment by expcapitaldev** [comment]
breautek hi! thanks a lot for your activity here. FBSDKCoreKit https://github.com/CocoaPods/Specs/blob/master/Specs/9/b/5/FBSDKCoreKit/17.0.0/FBSDKCoreKit.podspec.json#L13 is required 12.0
you can try add in any your plugin and do clean build.

`<podspec>
			<config>
				<source url="https://cdn.cocoapods.org/"/>
			</config>
			<pods use-frameworks="true">
				<pod name="FBSDKCoreKit" spec="17.0.0"/>
			</pods>
		</podspec>`
Can you share method or line in cordova-ios library which will be copy `deployment-target` value from config.xml to Podfile ? I see only https://github.com/apache/cordova-ios/blob/master/lib/Podfile.js#L40 which try to copy value but that value will be empty before installation first pod library

**Comment by expcapitaldev** [comment]
I think expected if I do clean build and have inside my main config.xml `<preference name="deployment-target" value="13.0" />` and do `cordova prepare ios` platform shoould be successfully added and prepared with all Pod dependencies without any additional changes. And now my platform should be ready for `cordova compile ios ` command. So, if current flow unexpected please close current issue but I think if my config.xml file has `<preference name="deployment-target" value="13.0" />` all Pod dependecies should be installed with 13.0 version.

**Comment by breautek** [comment]
>  but I think if my config.xml file has <preference name="deployment-target" value="13.0" /> all Pod dependecies should be installed with 13.0 version.

I don't think `deployment-target` does all pod dependencies, but it maintains the app's `Podfile` and that is what I observed in the steps I've taken as detailed in https://github.com/apache/cordova-ios/issues/1422#issuecomment-2065289819

If you're still reproducing the issue then confirm that you're running the latest cordova CLI and platform version and share sample project that reproduces the issue that we can look at. If a sample reproduction project cannot be provided then I don't think there's anything we can do to move this forward.

**Comment by faugusztin** [comment]
Reproduction case with order of steps where pod installation fails is [at my repository](https://github.com/faugusztin/cordova-ios-bug-1422) with cordova-ios 7.1.1. 

What triggers it is if we have config.xml and package.json configured with the plugin which requires increased deployment-target and then we run `cordova prepare` or `cordova platform add ios`

- either of those two commands calls cordova-lib to download the platform if the platform doesn't exist in the platforms directory. Up until the platform is ready, any ConfigParser for config.xml grabs the project root config.xml.
- after platform is created, there is a new config.xml inside platforms/ios/_PROJECT_NAME_/config.xml. This config.xml doesn't have the deployment-target set at this moment.
- restore-util.js inside cordova-lib is called, which identifies the need to install plugins based on package.json
- it then calls cordova-ios lib/Api.js addPlugin method
- addPlugin then sees plugin requires pods, adds the required changes to Podfile, and then runs `pod install --verbose`, which fails, because Podfile iOS target is set to default value of 11.0, as platforms/ios/_PROJECT_NAME_/config.xml doesn't contain the deployment-target property.
- this all happens before cordova-ios/lib/prepare.js is called, which then calls the updateConfigFile method inside the same file, which sets the deployment-target in config.xml. But this is too late for the Podfile generation and pod install commands executed withing the addPlugin method in previous step.

The reason for this order is in [prepare.js](https://github.com/apache/cordova-lib/blob/12.0.1/src/cordova/prepare.js). The order here is:
- add platforms from config.xml ([prepare.js](https://github.com/apache/cordova-lib/blob/12.0.1/src/cordova/prepare.js#L37) -> [restore-util.js](https://github.com/apache/cordova-lib/blob/12.0.1/src/cordova/restore-util.js#L35))
- add (install) plugins from config.xml - ([prepare.,js](https://github.com/apache/cordova-lib/blob/eb00bdca9d44b903eb38e1bef5d73d41386b88e3/src/cordova/prepare.js#L48) -> [restore-utl.js](https://github.com/apache/cordova-lib/blob/eb00bdca9d44b903eb38e1bef5d73d41386b88e3/src/cordova/restore-util.js#L158))
- prepare each platform ([prepare.js](https://github.com/apache/cordova-lib/blob/eb00bdca9d44b903eb38e1bef5d73d41386b88e3/src/cordova/prepare.js#L52))

There are two solutions i can think of:
- adding the platform should already merge the platform specific settings present in config.xml from the project root into the platform specific config.xml. That would be somewhere inside the [lib/Api.js createPlatform](https://github.com/apache/cordova-ios/blob/a8f9c5726af012e4efa60b222857ae0252c47099/lib/Api.js#L119) method.
- alternatively pod install commands shouldn't be executed within cordova-ios until [lib/prepare,js upateConfigFile](https://github.com/apache/cordova-ios/blob/a8f9c5726af012e4efa60b222857ae0252c47099/lib/prepare.js#L141) method is executed, as that is the moment when the config.xml file is actually up to date with settings from the project root config.xml.
- within cordova-lib/prepare.js swap the order of prepare and plugin install, that is call platform prepare first, then add plugins (but this is both a change outside cordova-ios and also possibly a breaking change if someone relies on current order of calls)

**Comment by faugusztin** [comment]
For now, the only reasonable workaround for this issue is to modify [cordova-ios/templates/project/App/config.xml](https://github.com/apache/cordova-ios/blob/master/templates/project/App/config.xml) (or `__PROJECT_NAME__` instead of `App` in 7.1.1 and older) either after npm install or by making a customized version of cordova-ios with the required change and installing that in place of cordova-ios using the npm custom alias notation.
And the required change would be adding the deployment-target in that config.xml template directly. That way the project would default to whatever deployment-target you set in the customized default config.xml, thus pod install commands (which executed by platform add before root config.xml changes are transfered to platform config.xml) would succeed. 

The actual solution would be obviously to change the project creation process, so config.xml definitions are transfered to platform config.xml much sooner in platform add process, before any plugins are ever tried to be installed.

**Comment by dpogue** [comment]
Thanks for clearly explaining the problem and showing the reproduction steps!

I think I agree that setting the deployment target version during project creation makes sense, if it exists in the root config.xml. I tried to take a quick skim through the JS code to find out when/where exactly root config.xml stuff is copied to the platform file, but didn't find it and can't remember the details. I saw a lot of stuff about config munging for `edit-config` and `config-file`, which obviously isn't safe to do before plugins have been installed. So if it's as simple as copying config.xml then it should be okay, but otherwise we might need to special case this particular preference during creation.

**Comment by faugusztin** [comment]
The [src/cordova/prepare.js](https://github.com/apache/cordova-lib/blob/master/src/cordova/prepare.js) file has a hooksRunner promise chain which calls in succession:
- fires the before_prepare hook
- restore.installPlatformsFromConfigXML (creates the platform structure from the default template files)
- processing various options into an options object
- restore.installPluginsFromConfigXML - installs plugins. This is where this use case fails, because for now, the config.xml is still the one from the cordova-ios template. Adding a plugin with a cocoapod dependency, which required a higher deployment target in this step causes Podfile to contain lower deployment target (as it is not yet written to config.xml, thus not picked up the Podfile.js logic), which then stops the process.
- module.exports.preparePlatforms - this one actually updates the config.xml inside the platform/ios folder based on the root config.xml.
- fires the after_prepare hook

> I tried to take a quick skim through the JS code to find out when/where exactly root config.xml stuff is copied to the platform file, but didn't find it and can't remember the details. 

https://github.com/apache/cordova-ios/blob/master/lib/create.js#L78 in method provideProjectTemplate ther is a call for `fs.cpSync(this.options.templatePath, this.project.path, { recursive: true });` which does that task.

> I saw a lot of stuff about config munging for `edit-config` and `config-file`, which obviously isn't safe to do before plugins have been installed. So if it's as simple as copying config.xml then it should be okay, but otherwise we might need to special case this particular preference during creation.

Alternatively pod install shouldn't be called in the `restore.installPluginsFromConfigXML` step if it is initial platform creation, but i am unsure if that is even possible. But this could break someones plugin, if they would modify files downloaded by pod install in after_plugin_install or after_plugin_add (unsure how realistic this is, but it is an option), so not sure if this is a valid way to solve the issue. 

Last alternative is for callers of Podfile.js to pick minDeploymentTarget based on config.xml from root too, thus it would be 4 options:
- (existing logic) pick deployment-target from platform/ios/App/config.xml 
- (new code) look at project root config.xml widget->preference[name="deployment-target"]
- (new code) look at project root config.xml widget->platform[name="ios"]->preference[name="deployment-target"]
- (existing logic) hardcoded default in Podfile.js (11.0 in cordova-iox 7.x, 13.0 in cordova-ios 8.x)

**Comment by faugusztin** [comment]
Confirming the fix as working for me.
