### ISSUE TITLE
iOS universal icon support

### ISSUE THREAD

**Issue by geoidesic** [apache/cordova-ios#1462]
# Feature Request
iOS universal icon support
https://cordova.apache.org/docs/en/12.x/config_ref/images.html#ios

## Motivation Behind Feature

iOS supports using a single 1024 size universal icon. Why doesn't cordova? It's such a pain having to configure icons; it's really the most time consuming thing in app deployment, so why force us to do it when it's so unnecessary?

## Feature Description

Add the ability to use a universal icon in config.xml
If this already exists, then please, for the love of god, update the docs!

## Alternatives or Workarounds

Painfully watching the sand of my life drain to the bottom of the hourglass. 
Grinding is for games, not deployments!

**Comment by breautek** [comment]
It was proposed last year via https://github.com/apache/cordova-ios/pull/1309 but at the time the community voted to continue support for iOS 11, which meant we couldn't support the universal icon (because XCode supports one or the other, but not both, or something to that effect).

It also prevents users from building specific icon renderings for specific sizes, which one might do if their particular icon resource doesn't scale well depending on the nature of the graphic. So there was some push-back on that front as well when this was being discussed last year.

Personally I'd like to see support for single universal icon but even if the min iOS deployment is increased to 12, it might involve more tooling to determine if the project should be "universal" icon mode vs multi-icon mode to support both paths.

**Comment by breautek** [comment]
> Firstly, I believe Apple's new minimum build target is 12. So there's that.

Not very accurate. iOS 11 is out of support of XCode, but it doesn't prevent projects from specifying deployment target of iOS 11 and it will work (with warnings).

> Secondly, I don't see why both can't be supported. It's just a matter of putting the right information and assets into the project, based off configuration.

It's not really a question of it can or can't be supported. Comes down to someone willing to volunteer their time to add the feature to support both paths and all the edge cases like switching from one mode to another and clean up the resources accordingly, etc. e.g. jcesar attempted in #1309 but he did it in a more simple fashion where it only supported the universal path and there was some push-back (I'd have to look for the dev mailing list thread if you'd like a reference) so we ended up abandoning the PR.

To be clear I was just summarising the history so that if someone wants to pursue this, they can understand the context.

**Comment by geoidesic** [comment]
Ok that makes sense.

I'll have go if you can help me with two things:
1. How do I connect my globally installed `cordova` to a local copy of `cordova-ios`? Or is that the wrong approach?
2. How do I get a reference to config.xml's data?

**Comment by breautek** [comment]
> How do I connect my globally installed cordova to a local copy of cordova-ios? Or is that the wrong approach?

They are two separate packages that are decoupled. If you fork/clone `cordova-ios` you can install the dev version to a test project by doing:

```
cordova platform add ../cordova-ios
```

Where `../cordova-ios` is your git checkout. You'll need to run `npm prepare` inside your cordova-ios checkout once to generate the `cordova.js` file.

`cordova-lib` is a package that has the standard commands (build, prepare, run, clean, etc) but the platform code implements those commands to manage the underlying native project. So you'll likely be making changes in https://github.com/apache/cordova-ios/tree/master/lib for the most part. e.g. https://github.com/apache/cordova-ios/blob/master/lib/Api.js#L223 is the entry point from cordova-lib to platform-specific code for the `prepare` command, which is responsible for generating/manipulating the xcode project. The actual implementation for `prepare` for iOS is at https://github.com/apache/cordova-ios/blob/master/lib/prepare.js#L41

> How do I get a reference to config.xml's data? Or would it be better as a setting in build.json?

The command context should have a reference to the config in some way. I'm not as familiar with the cordova-ios project as much as I am with the android platform, but it looks like it's parsed at https://github.com/apache/cordova-ios/blob/master/lib/prepare.js#L44

`_config` should be some sort of structured object. I think there are APIs to get "platform"-specific config, you can see how icons is currently read for an example.

Consider joining the community [slack](https://join.slack.com/t/cordova/shared_invite/zt-z70vy6tx-7VNulesO0Qz0Od9QV4tc1Q) for more dev assistance.

**Comment by geoidesic** [comment]
Oh wow. Ok that all went over my head.

What I meant was, when I run this command: `cordova do-some-sh1T ios` then that's not `cordova-ios` that's running that command, instead it's `cordova-lib` so how do I get `cordova-lib` to make use of my local checkout of `cordova-ios`?

**Comment by dpogue** [comment]
We definitely want to support the single 1024×1024 icon for the next major version (Cordova iOS 8), along with the new iOS 18 feature of dark mode and tinted icon variants, so I'm reopening this to track that.

**Comment by jcesarmobile** [comment]
> > Consider joining the community [slack](https://join.slack.com/t/cordova/shared_invite/zt-z70vy6tx-7VNulesO0Qz0Od9QV4tc1Q) for more dev assistance.
> 
> Amazing. It's taken about 2 years of working with Cordova for that link to manifest. I've been searching for the community. It's like a well kept secret! That should be somewhere in the docs or on the cordova website!!
It’s there
https://cordova.apache.org/contribute/

**Comment by geoidesic** [comment]
> It’s there https://cordova.apache.org/contribute/

Consider moving it to the home page. Currently it is hidden only where those who intend to become contributors would look.
