### ISSUE TITLE
Can't get push token on 8.0.0-dev

### ISSUE THREAD

**Issue by jcesarmobile** [apache/cordova-ios#1487]
# Bug Report

### What is expected to happen?
Be able to receive push notification token

### What does actually happen?
The push notification token is not received.

## Information
Using `@havesource/cordova-plugin-push` plugin, push notification token is no longer received on cordova-ios 8.0.0-dev.

### Command or Code
```
const push = PushNotification.init({
    android: {},
    ios: {
        alert: 'true',
        badge: true,
        sound: 'false'
    }
});
push.on('registration', data => {
    console.log('registrationId',data.registrationId);
    console.log('registrationType',data.registrationType);
});
```

### Environment, Platform, Device
any iOs version

### Version information
8.0.0-dev

This is most likely related to the new swift template since the plugin uses a category on the AppDelegate.
While `AppDelegate.h` file still exists, all what it does it to make the plugin compile, I think the category longer works since the methods are now called in `AppDelegate.swift`.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpogue** [comment]
After some experiments with @erisu and changing the plugin from using AppDelegate to using CDVAppDelegate, I suspect the underlying issue is that the (CDV)AppDelegate's `viewController` is no longer set to a CDVViewController instance, so when the plugin tries to look itself up by name, it can't.

I _really_ don't like relying on that, particularly since its unintuitive in the case of apps that embed a CDVViewController as part of a larger app, but I guess the safest option for backwards compatibility in 8.0.0 would be to set the CDVAppDelegate `viewController` to the first CDVViewController that has its `viewDidLoad` method called. The deprecation warning on the property should alert plugin authors that what they're doing isn't safe for future versions.

**Comment by jcesarmobile** [comment]
I have not tested with the CDVAppDelegate, but with the AppDelegate the problem isn’t just not getting the token on js, the method is not being called in native neither.
