### ISSUE TITLE
Failed to resolve host network app id

### ISSUE THREAD

**Issue by jonyking** [apache/cordova-ios#1489]
# Bug Report

## Problem
We can not start start the app after building via xcode.

### What is expected to happen?
Normal start of the App

### What does actually happen?
Xcode shows the following error: "Failed to resolve host network app id" 

## Information
XCode: 15.4
cordova-android: "^12.0.1",
cordova-ios: "^7.0.1",
cordova-plugin-keyboard: "^1.2.0",
cordova-plugin-splashscreen: "^6.0.2",
cordova-plugin-statusbar: "^4.0.0"
NPM: 10.8.1
Framework7:  8.3.2

### Command or Code
-

### Environment, Platform, Device
All iOS devices

## Checklist

- [ X] I searched for existing GitHub issues
- [ X] I updated all Cordova tooling to most recent version
- [X ] I included all the necessary information above

**Comment by breautek** [comment]
> Xcode shows the following error: "Failed to resolve host network app id"

This isn't an error, it's a warning, as indicated by its yellow background (instead of red). It will appear on any app using utilizing WKWebView and is very likely not related to your observed behaviour. It will also print on properly working WKWebViews as well.

<img width="1169" alt="Screenshot 2024-09-09 at 9 45 00 AM" src="https://github.com/user-attachments/assets/5d69d19c-4940-41fa-b4ae-1480d96ed264">

Without knowing exactly what the observed behaviour is, I can only speculate and I am assuming you're effectively seeing a blank WKWebView screen, but here are some things you can try:

1. Look for any other errors or console prints that might suggest failure to load your index document. These may include (but not limited to) plugins failing to load.
2. Test to see if you can connect the Safari Web Inspector ([See How](https://breautek.com/articles/debugging-cordova-apps.html) (Scroll to the iOS section)). Safari won't report on any log events or errors that occurred before the debugger was attached, but while the inspector is focused, you can press `cmd + r ` to refresh the webview. Any JS errors or log prints that occur on launch should be observable in the Safari Web Inspector. These may not be visible from the XCode console either and might give you insights on what is actually happening.

**Comment by breautek** [comment]
closing as stale.
