### ISSUE TITLE
Why is ios-deploy required for plain builds (without deployment)?

### ISSUE THREAD

**Issue by oliversalzburg** [apache/cordova-ios#420]
Why am I seeing this complaint when I'm not even trying to deploy? This happens on `cordova build`:
```shell
CordovaError: Promise rejected with non-error: 'ios-deploy was not found. Please download, build and install version 1.9.2 or greater from https://github.com/phonegap/ios-deploy into your path, or do \'npm install -g ios-deploy\''
```

**Comment by janpio** [comment]
My guess is this happens because of a "global" requirement check, triggered by this code: https://github.com/apache/cordova-ios/blob/46da4bc34495ec7bfe13c1ec1b4074dd2e82641a/bin/templates/scripts/cordova/lib/check_reqs.js#L145-L152

Can you post more of your output (and stacktrace if available) so we can better track this down?

**Comment by brodybits** [comment]
I get the following results from running `cordova build ios` with no `ios-deploy` installed:

```sh
CordovaError: Promise rejected with non-error: 'ios-deploy was not found. Please download, build and install version 1.9.2 or greater from https://github.com/phonegap/ios-deploy into your path, or do \'npm install -g ios-deploy\''
    at cli.catch.err (/Users/brodybits/.nvs/node/8.12.0/x64/lib/node_modules/cordova/bin/cordova:29:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

I am marking this as a bug since I think `ios-deploy` which has viral GPL v3 license should not be required to *build* an app from the command line.

I think we should make some better distinction between *required* build tools and *recommended* build tools.

**Comment by janpio** [comment]
It is required to deploy to iOS devices. I don't think there is a distinction if a requirement is for building or running.

**Comment by oliversalzburg** [comment]
My guess is this is the culprit:
https://github.com/apache/cordova-ios/blob/004b8300456816cc614d229e85a35a8bc37d363d/bin/templates/scripts/cordova/lib/build.js#L113

**Comment by brodybits** [comment]
@oliversalzburg I think you did identify the right "culprit", not so sure that I would follow your logic concerning `check_reqs.run()` 100%. I think `check_reqs.run()` which checks for `xcodebuild` tool would be used for both simulator and device.

Considering that `check_reqs.check_ios_deploy()` is also called in <https://github.com/apache/cordova-ios/blob/11170612a51b9cbeb32f550e6a07791ac7814646/bin/templates/scripts/cordova/lib/run.js#L58>

a quick solution could be to simply remove `check_reqs.check_ios_deploy()` check from: <https://github.com/apache/cordova-ios/blob/11170612a51b9cbeb32f550e6a07791ac7814646/bin/templates/scripts/cordova/lib/build.js#L113>

The downside of this quick solution is that it would lead to a case where an attempt to do `cordova run ios --device` with no `ios-deploy` installed would first do the build and then fail with the "ios-deploy was not found" error.

I think a better solution would be to adapt `cordova-lib` and `cordova-ios` so that an attempt to do `cordova run ios --device` with no `--nobuild` option would somehow check the result of `check_reqs.check_ios_deploy()` before attempting to build and run. This kind of solution would definitely need an adaptation to <https://github.com/apache/cordova-lib/blob/master/src/cordova/run.js>. I think the hard part would be getting the interface between `cordova-lib` and `cordova-ios` right.

I cannot promise when I would personally have time to work on this one. I suspect the other cordova-ios experts are pretty busy right now. PRs on cordova-lib and cordova-ios for review would be very welcome.

**Comment by oliversalzburg** [comment]
Doesn't this piece already take care of the identical check for `cordova run ios`?

https://github.com/apache/cordova-ios/blob/46da4bc34495ec7bfe13c1ec1b4074dd2e82641a/bin/templates/scripts/cordova/lib/run.js#L58

And that check happens before the project would be built prior to deployment. It seems to me like that check in `build.js` just needs to be removed.

**Comment by aflofo** [comment]
Why does https://github.com/phonegap/ios-deploy redirect here was there an ownership switch. I am very confused.

**Comment by bizzareshishir** [comment]
All I had to do was disconnect my real device (iPhone X) from my Mac.

**Comment by jannikco** [comment]
> All I had to do was disconnect my real device (iPhone X) from my Mac.

F**K! It works. I was getting mad over this. Thank you so much!

"** BUILD SUCCEEDED **" 💪

**Comment by AlexAstilean** [comment]
> All I had to do was disconnect my real device (iPhone X) from my Mac.

I just spent over 2 hours trying to find a solution. This was the real problem. 

Thank you so much !

**Comment by brodybits** [comment]
> Why does https://github.com/phonegap/ios-deploy redirect to https://github.com/ios-control/ios-deploy. Was there an ownership switch.

Yes. As you likely know, Cordova was originally born as PhoneGap. PhoneGap was *mostly* renamed as Cordova in order to avoid trademark issues in the Apache project. I think the iOS tools were moved to a separate org to keep them independently under other licenses. They still use PhoneGap for PhoneGap Build and other tools by Adobe. And the confusing part is that they made a PhoneGap CLI which is a copy of the Cordova CLI. @shazron and @purplecabbage could probably explain this better.

**Comment by brodybits** [comment]
> > All I had to do was disconnect my real device (iPhone X) from my Mac.
> 
> I just spent over 2 hours trying to find a solution. […]

I just created and added the **help wanted** label, hope we can get this one fixed soon. I would likely favor my “better solution” that I proposed in <https://github.com/apache/cordova-ios/issues/420#issuecomment-425132074>.

**Comment by jpike88** [comment]
argh just ran into this... thank god someone told me I had to unplug my iPad. was about to go down a rabbit hole

**Comment by BrianRosamilia** [comment]
I almost never clone+fix global packages to deal with issues like this, so I added this to my readme instead.  It's instructions on how to remove this line since it's a bit annoying for my personal workflow.

-----------
## Fix phone plugged in testing

`mdfind check_reqs.check_ios_deploy`

Comment out line in any `build.js`
-----------

Should be totally safe since the return value is actually never used (and mdfind is super fast 🥇)

**Comment by maxegghead** [comment]
-> BrianRosamilia 
Thanks for this, really useful, much better to be able to run new builds without keep unplugging my phone.  Especially as every time I plug in my phone I get asked if I trust my macbook, and have to type in my 6 digit lock code (slowly as the screen keyboard can't keep up with a fast rate of typing).  sheesh Apple.

**Comment by jpike88** [comment]
@maxegghead do yourself the favour and remove the need to ever test Cordova outputs on a real device, just deploy to a beta testing platform instead. I wrote a whole build pipeline composed of fuse-box tasks with some Cordova cli calls to upload the build to TestFlight etc. It’s somehow much smoother than trying to test on device

**Comment by mattfroese** [comment]
> > All I had to do was disconnect my real device (iPhone X) from my Mac.
> 
> F**K! It works. I was getting mad over this. Thank you so much!
> 
> "** BUILD SUCCEEDED **" 💪

My gosh. Thank you. This worked for me.

**Comment by donni106** [comment]
> All I had to do was disconnect my real device (iPhone X) from my Mac.

:o wow, so glad to found you comment @shishirshettygit

**Comment by Hussain-AboAlamal** [comment]
> All I had to do was disconnect my real device (iPhone X) from my Mac.

thanks a lot, you saved my day

**Comment by pranayreddy123** [comment]
close xcode and run 'ionic cordova build ios'. for me it worked

**Comment by Mehuge** [comment]
This issue also breaks the code signing settings in the project. Specifically, if I build the project with a device plugged in, the build fails with the promise rejection, the resulting project code signing settings are broken. No team is selected and Xcode displays a warning about having mixed code signing settings.

Unplug the phone, build, and the xcode project signing settings are correctly defined.
