### ISSUE TITLE
iPad Pro 2018

### ISSUE THREAD

**Issue by lougreenwood** [apache/cordova-ios#465]
Hello,

I've just had an iOS app rejected because of scaling on the iPad Pro - when I test in Simulator, I see black bars on both the 11" & 12.9" new iPads (2018).

I'm using Cordova 8.1.2, Cordova-iOS 4.5.5 & Xcode 10.1.

Does anyone have any advice on how to build the app so it renders correctly on iPad Pro? My app looks great on iPhone Xs/Xs Max, so I suppose I'm correctly using `safe-area-inset`.

Thanks!

**Comment by dpogue** [comment]
You'll need to provide a splash screen image of the right size to make the app use the full screen space.

The easiest way to do this is to use [Launch Storyboard images](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-splashscreen/index.html#launch-storyboard-images) instead of trying to provide a different image for each device.
