### ISSUE TITLE
iOS 12 / UIWebView Keyboard covers INPUT elements at the bottom of page

### ISSUE THREAD

**Issue by dpolivy** [apache/cordova-ios#472]
I've noticed a regression/change in behavior with iOS 12 on our Cordova app using UIWebView. When we have `<input>` elements at the bottom of the page, tapping to insert focus brings up the iOS keyboard, which promptly covers the element and makes it impossible to see/edit what you are typing. You also cannot manually scroll the page higher to make it visible. It seems the keyboard now overlays the UIWebView, instead of the UIWebView adjusting to accommodate the space above the keyboard.

This is easily reproducable with @dpogue's repro case for the WKWebView issue:

https://github.com/dpogue/WKScrollTest

Simply change [this line](https://github.com/dpogue/WKScrollTest/blob/visual-viewport/WKScrollTest/ViewController.swift#L12) to `true`, delete Test Case 8 from the HTML, and run on an iOS 12+ device. Scroll to the bottom of the page, and tap in the input in Test Case 7. The keyboard covers the input.

If you run this same code on iOS 11 or earlier, the viewport adjusts so the input is visible above the keyboard.

This seems similar to #417 but is a distinct issue, as there are no ill-effects once the keyboard is dismissed.

Anyone else seen this/have a workaround or solution?

<details>
<summary>
Example screenshots
</summary>

Here it is on iOS 12 on iPhone XR:

![image](https://media.giphy.com/media/vRMrmmq7AXgJfbwZnb/giphy.gif)

Here it is working on an iPhone 6 with iOS 9.3:

![image](https://media.giphy.com/media/3izaxtuSSjcf6lgVnr/giphy.gif)

</details>

**Comment by dpogue** [comment]
I suspect this is the case they were trying to fix when Apple added https://github.com/WebKit/webkit/commit/0ff63c48b7456d6b72b0e751a600d9e3d14dbdeb to WKWebView (unfortunately that change is now causing #417).

I also suspect this was never backported to UIWebView 😞 
It's *probably* not something that we can fix at the Cordova level, without extremely ugly hacks.

**Comment by dpogue** [comment]
Filing a radar on bugreporter.apple.com is probably the best plan of action.

**Comment by JKershaw** [comment]
This isn't a great solution, but a bit of a hack for anyone (like me) desperately trying to fix this bug.

Adding a tall div at the bottom of every page for iOS devices gets around the issue. 

It gives enough runoff room for the text input to be scrolled into place. The downside is you now have a blank section at the bottom of every page, but I'd prefer that to not being able to use a text input until this is fixed properly.

**Comment by dpolivy** [comment]
FWIW, Apple resolved my bug as a duplicate of another bug, which they said was resolved in iOS 12. Clearly they didn't even try the repro project on the latest iOS build. Any other suggestions on how to escalate?

**Comment by mgerstenblatt** [comment]
Anyone find a workaround for this yet for UIWebView?

**Comment by alexyazvinsky** [comment]
Any updates on that? With WKWebView we have the same issue with covered inputs in the bottom.

**Comment by dpolivy** [comment]
No luck on my end. I filed another bug on the issue with the same details, and actually asked them to use the repro project to verify -- so far it is still open with no feedback from Apple.

I also used a Tech Support incident to try and ask for code level support on this. The response was "UIWebView is deprecated, use WKWebView" and if that doesn't work to file a bug on WKWebView. The second response was to just use a UITextField instead. So, clearly, I'm not getting anywhere with Apple directly. I haven't had time to sit and look at a code workaround, but maybe I can adjust the UIWebView sizing based on the keyboard appear/disappear notifications and that will help...

**Comment by ronnievdc** [comment]
A temporary workaround could be by setting the css of the `<body>` element to `position: fixed`.
Inside the body an scrolling element with `position: absolute; overflow-y: auto` can be created.

I created an example: https://github.com/Owello/ui-web-view-keyboard

**Comment by lptnmachine** [comment]
Since Apple apparently isn't hurrying to fix this (if they ever will), here's a workaround that works for us and might work for you:
First, the problem only seems to occur if you added `viewport-fit=cover` to your meta-tag. Since that's needed to support the notch removing that isn't really an option; the workaround that worked for us was using the [cordova-keyboard-plugin](https://www.npmjs.com/package/cordova-plugin-keyboard) and setting the `shrinkView `option to `true`. This WILL change some behaviour on opening and closing the keyboard, so you should definitely check if the rest of your application still works as intended if you try this.
This mostly got rid of the problem for us - except for cases where the page was shorter than the viewport. This might just be a side effect on how we handle overlays in our project, but on opening the keyboard there's some black space added to the bottom of the site. We worked around that by using JS to set the `min-height` of the `html `element to the pixel value of the viewport height (instead of `100vh`, in our case). Again, this changes some behaviour, especially with scrolling on keyboard opening, but most of that can easily be mitigated with a few lines of JS and the events that the Keyboard plugin makes available.
It's not perfect, but it's far better than any other solution I found.

**Comment by shuppert** [comment]
I tried using shrinkView as @lptnmachine suggested but it broke the InAppBrowser in my app.

The fix for me was this; https://github.com/apache/cordova-ios/issues/417#issuecomment-466520675

The globally set viewport-fit=cover was causing issues on iPad's running iOS 12.x since it's only needed on the iPhones with the notch.

**Comment by VenkatRaj2017** [comment]
I tried as **@ronnievdc** suggested but its creates new bug "**white blank screen**" when I click on input element.

Any solution plz.

**Comment by sjoerdloeve** [comment]
@ronnievdc Thanks for you comment, helped me out on iPad with iOS 12.2.

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version (using WKWebView, since UIWebView is no longer supported), please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
