### ISSUE TITLE
[Feature Request] Set XCode project settings from buildConfig JSON

### ISSUE THREAD

**Issue by l3ender** [apache/cordova-ios#506]
The command `cordova platform add ios` generates an XCode workspace (if it doesn't exist), but the workspace won't have settings that are configured in a `build.json`.

For example, I run the following commands:
```
cordova platform add ios
cordova run ios --buildConfig build.json
```

Here is my `build.json`:
```
"ios": {
    "debug": {
      ...
      "buildFlag": [
        "-UseModernBuildSystem=0",
        "ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=YES"
      ]
    }
}
```

This command allows you to run the iOS app on device/simulator, and it will correctly build/compile based on properties in the `buildConfig` file. If I now use XCode to open the workspace that was generated by `cordova platform add ios`, the workspace that does not have the same workspace settings configured (in my scenario, `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` is not configured). Any settings will need to be manually configured in XCode if I want to open the project in XCode and run the app from there.

I think expected behavior would be that if I run the app from the Cordova CLI OR have the CLI generate an XCode workspace and run the app from there, the app should react the same.

**Comment by godexsoft** [comment]
The real question is why is there debug and release sections in the json.build but only either one makes it to BOTH debug/release sections in the xcode project depending on the --debug/--release switch in cordova CLI. it does not make too much sense. A much better way would be to populate xcode project with both debug and release profiles and then just compile/build the correct version depending on the cli switch.

Is there anything i'm missing? maybe i did not understand how to use it correctly?

**Comment by janpio** [comment]
@godexsoft You are definitely in the wrong issue - please create a new one for your problem - from a first reading it might be worth looking into what you describe, but not here in @l3ender 's unrelated issue. Thanks!

**Comment by godexsoft** [comment]
> @godexsoft You are definitely in the wrong issue - please create a new one for your problem - from a first reading it might be worth looking into what you describe, but not here in @l3ender 's unrelated issue. Thanks!

seemed like a related issue to me. created a new one just now: #507 
Thanks

**Comment by l3ender** [comment]
> > @godexsoft You are definitely in the wrong issue - please create a new one for your problem - from a first reading it might be worth looking into what you describe, but not here in @l3ender 's unrelated issue. Thanks!
> 
> seemed like a related issue to me. created a new one just now: #507
> Thanks

**Comment by l3ender** [comment]
Whoops! Didn't mean to close.

**Comment by janpio** [comment]
@l3ender What do you think about my response? Does this make sense to you?

**Comment by l3ender** [comment]
@janpio Yes, it makes sense. So it seems like this makes sense as a feature request?

**Comment by janpio** [comment]
Yes, let's track this as a possible `enhancement`. Someone will have to think through all the implications this might have.

**Comment by dpogue** [comment]
I looked into this, to see if we might be able to copy the buildFlag values to an xcconfig file for preserving between builds, but I don't think it's going to be possible. There are (at least) 2 issues that prevent this.

1. Not all build flags are options that can be set via xcconfig.

  In the examples given, `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=YES` could be added to an xcconfig file and it would work as expected. However, something like `-UseModernBuildSystem=0` or `-quiet` is a command-line option to the xcodebuild tool and there's no way to set those (some of them may have their own variables that can be set in xcconfig, but it's not a 1-to-1 mapping that we could easily transform at prepare time).

2. Distinguishing between build.json-injected flags and plugin-injected flags when flags are removed.

  Assuming that we write all the flags from build.json to the xcconfig file, we wouldn't have a way of distinguishing those build flags from ones that a plugin injects to the xcconfig file. Hence, if a flag is removed from build.json, and we want to remove it from the xcconfig, it's impossible to know which lines are safe to remove.
  
  This also opens the door for conflicting flags if something is specified in both build.json and a plugin. Right now, build.json wins because it provides the flags as part of the xcodebuild command line, but if the flags were combined into an xcconfig file there could be issues relating to order in which plugins are added and flags getting duplicated with different values.

I think the (ugly) workaround would be to add a hook script to your Cordova project that injects the flags you want into an xcconfig file. Those would persist between builds and in Xcode, but the responsibility for getting the right flag names and handling flag conflicts/removals would fall on you as the app author.
