### ISSUE TITLE
WKWebView built-in support status

### ISSUE THREAD

**Issue by guylando** [apache/cordova-ios#534]
It was said here: https://cordova.apache.org/news/2018/08/01/future-cordova-ios-webview.html that cordova-ios 5 will add easy transition to wkwebview however I do not see any mentioning of wkwebview in cordova-ios 5 release: https://cordova.apache.org/announcements/2019/02/09/cordova-ios-release-5.0.0.html

Where can we found a roadmap or status on WKWebView support (and status of its limitations which gradually are fixed)?

Basically looking for an updated https://cordova.apache.org/news/2018/08/01/future-cordova-ios-webview.html post since 6 months passed and this is a hot topic now that UIWebview is deprecated and ios 13 is going to be released in 4-5 months https://www.macworld.co.uk/news/iosapps/ios-13-release-date-3678394/.

Also what is the chance that apple will remove UIWebView from ios13? it will break thousands of apps so maybe it will not happen in ios 13? Anyone has some inside information on this? Since ios 13 will be released in 4-5 months as the link above says then if it can be confirmed that UIWebView will be removed it will influence the priority given for upgrading to WKWebView. Maybe they will not touch existing apps and just prevent uploading new apps/updates which contain UIWebView?

The main problems of upgrading to WKWebview are:
1. Iframes support/bugs
2. Cookies support/bugs
3. CORS support/bugs
4. WKWebView does not seems stable enough such as the keyboard scroll bug and other bugs. Short search of people who attempted to upgrade to WKWebView shows hundreds of complaints and problems.

**Comment by janpio** [comment]
Great question(s).

Some context from the comments to the 5.0.0 release blog post:

> jcesar:
> When the post was written we didn't know Apple will require Xcode 10 in March, so considering the resources we have, we could't make the WKWebView integration on time.
So better have a 5.0 compatible with Xcode 10 before Apple's deadline than still being on 4.x, not properly working on Xcode 10, because we were waiting for the WKWebView integration.

https://cordova.apache.org/announcements/2019/02/09/cordova-ios-release-5.0.0.html#comment-4338739841

That explains why 5.0.0 does not have "promised" WKWebView support. Might have been smarter so say "some future release", and not `Cordova 5` in https://cordova.apache.org/news/2018/08/01/future-cordova-ios-webview.html ;)

**Comment by guylando** [comment]
@janpio Actually I saw that comment however that answer does not clarify the timelines/roadmaps and the other things I asked. My main concern is for our app not to be "banned" because of the UIWebView and since ios 13 comes our in 4-5 months it raises concerns related to exact timeline/roadmap related to WKWebView and related to if apple are really going to "ban" UIWebView in ios 13.

**Comment by janpio** [comment]
> Actually I saw that comment however that answer does not clarify the timelines/roadmaps and the other things I asked.

I know that, but I can't give you those answers as I personally just don't know. I could give you feedback and context on your first paragraph, so that's what I did.

Your response sounds a bit confrontative (instead of just "Thanks for that info" or anything else appreciative), which makes me regret a bit that I replied at all.

We are just a group of volunteers here, working on this mostly in our free time, not a company you are paying to deliver you solutions to your problem (although I am sure some contributors would be happy to work on Cordova via a contract!). We are more than happy to accept any help - Join us on our Cordova Slack in #dev if you want to contribute.

---

That being said, your concerns are of course valid and I completely understand - and actually share them! 

I can tell you that we are doing everything we can to get any necessary changes in. Right now this means working on the big Cordova CLI 9 release, which Cordova iOS 5 and Cordova Android 8 were part of (and that includes almost _all_ our other many packages). After that, someone will probably focus on WKWebView stuff again.

---

> Also what is the chance that apple will remove UIWebView from ios13? it will break thousands of apps so maybe it will not happen in ios 13? Anyone has some inside information on this? Since ios 13 will be released in 4-5 months as the link above says then if it can be confirmed that UIWebView will be removed it will influence the priority given for upgrading to WKWebView. Maybe they will not touch existing apps and just prevent uploading new apps/updates which contain UIWebView?

I personally can't imagine that they really will remove UIWebView. But who knows, sometimes they take drastic measure. Just yesterday I couldn't take part in a video conference via my laptop because my earbuds have a different plug than my computer 🤷‍♀️ 

But this personal opinion/hope doesn't change the fact that WKWebView is better in many ways (and unfortunately much worse in others) - and the future that Apple wants for us. So this will definitely happen.

**Comment by guylando** [comment]
Thanks for the info. The goal of this issue was to get some "internal" info from the developers or hopefully from some apple insider in light of the big change coming soon. My last reply goal was to clarify that I was aware of that comment in that link in order to prevent someone from closing this issue because of thinking that it answered the questions I asked.

**Comment by guylando** [comment]
Also from what I been reading it seems that part of the changes required to make the transition to WKWebView smooth is on the apple side and not on cordova side so regarding that of course I dont expect anybody from the cordova developers to know a timeline but maybe someone is aware of the latest progress from the apple side and if it is even real to expect things like iframe to ever work in WKWebview

**Comment by mgatto** [comment]
For iframes, could InAppBrowser be a useful replacement in these use cases?

**Comment by jcesarmobile** [comment]
Apple is not going to ban the UIWebView. But as it’s deprecated they can just remove it in a future release.
FYI, UIWebView is still on iOS 13 beta.

**Comment by guylando** [comment]
@jcesarmobile just to clarify what you wrote: if they don't ban it but remove it, you mean that it will not work on new ios versions and work only on old ones? basically that would make UIWebView undesirable to choose to developer with.

**Comment by jcesarmobile** [comment]
I mean they won’t ban apps because they use it.
But yeah, once they remove it, apps won’t work on new iOS version. For now iOS 13 seems ok, but of course people should move ASAP as we can’t know when that will happen.

**Comment by Phil15634280** [comment]
FYI: https://forums.developer.apple.com/thread/122114
Although Apple will not "ban" an app, it does seem as though they will stop accepting new apps in the future (no mention of exactly when).

**Comment by jacobg** [comment]
It sounds like it means submission of any app for review, including updates on existing apps.

**Comment by janpio** [comment]
Big current discussion about this here: https://github.com/apache/cordova-ios/issues/661

**Comment by guylando** [comment]
Seems like #661 is a duplicate of this issue.

**Comment by jcesarmobile** [comment]
Not really, this is about the integration, the other one was about removing the UIWebView entirely. It already has a PR that allows to do it in compile time with a preference, which allows to strip it without making it a breaking change and without the need of integrating the WKWebView into cordova-ios (as long as there is a WKWebView plugin installed). So the other is more short term issue for next minor release and this one more long term for next major release.

**Comment by erisu** [comment]
Closing as `UIWebView` code has been removed from master and WKWebView has been added to core. #773
