### ISSUE TITLE
Selecter wheel leaves a viewport shifted in iOS 12 (and onwards)

### ISSUE THREAD

**Issue by AnkitTheCoder** [apache/cordova-ios#585]
# Bug Report

## Problem
When using a Cordova on iOS 12, similar to #417, the viewport is shifted. Except that rather than keyboard being the trigger of that shifted viewport, it is the select/dropdown wheel.

### What is expected to happen?
It is expected that upon selecting an option from the list of options and pressing the 'done' button, the viewport will shift back to where it was prior to being pushed up by the options wheel.

### What does actually happen?
From iOS 12, the viewport does not return to its expected position but instead stays pushed up.

## Information
This does not appear to be an issue for iOS versions prior to 12.

### Command or Code
Any dropdown that requires an option selection triggers this behavior.

### Environment, Platform, Device
All devices using iOS version 12.

### Version information
Cordova plugins via meteor framework.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpogue** [comment]
The selection wheel (and date/time pickers) are all considered special types of "keyboards" by iOS, so they'll behave the same way as a standard keyboard. In particular, this bug is triggered because they scroll the WebView to the focused input element.

I'm going to close this in favour of keeping all the discussion at #417, but this is another symptom of the problem in WebKit and should be reported to Apple.
Please file a radar report at http://bugreporter.apple.com!
