### ISSUE TITLE
`cordova run ios --target iPhone-X --emulator` builds for "iPhone SE Simulator"

### ISSUE THREAD

**Issue by janpio** [apache/cordova-ios#593]
See the last successful local-to-Travis build of paramedic:
https://travis-ci.org/apache/cordova-paramedic/jobs/517056009

```
...
cordova-paramedic: running command cordova run ios --no-telemetry --no-update-notifier --target iPhone-X --emulator --buildFlag=-UseModernBuildSystem=0
$ cordova run ios --no-telemetry --no-update-notifier --target iPhone-X --emulator --buildFlag=-UseModernBuildSystem=0
Building for iPhone SE Simulator
...
```

The code before somehow seems to have chosen `iPhone-X` as an appropriate "target" value, but `cordova run ios ... --emulator` then decides to build for iPhone SE Simulator instead.

**Comment by erisu** [comment]
This issue is no longer valid.

Similar issues have been reported in other tickets, tested, and confirmed to not be an issue with the latest cordova-ios platform.

Since Paramedic typically utilizes the main branch or the latest release, this issue should not persist.

If the problem persists, please open a new ticket.
