### ISSUE TITLE
Arrays in plist files can not be adjusted with edit-config

### ISSUE THREAD

**Issue by oliversalzburg** [apache/cordova-ios#613]
# Bug Report

### What is expected to happen?

When you want to have device-specific orientation options, like only portrait on phone, but allow landscape on iPad, you'd want to use `edit-config` to adjust your `.plist` accordingly.

### What does actually happen?

When you use `edit-config` to make adjustments not covered by the `preference` for orientation, they will not be persisted to the `.plist` for your iOS project.

## Information

> Possibly related to https://github.com/apache/cordova-common/commit/9c6cda3db766c3daa87e8e4f8cc65e818a9e6dfc (https://issues.apache.org/jira/browse/CB-13496)

The `edit-config` directives would be:
```xml
<edit-config file="*-Info.plist" mode="overwrite" target="UISupportedInterfaceOrientations">
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
	</array>
</edit-config>
<edit-config file="*-Info.plist" mode="overwrite" target="UISupportedInterfaceOrientations~ipad">
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
</edit-config>
```

The result will be (regardless of the configuration details above):
```xml
<key>UISupportedInterfaceOrientations</key>
<array>
  <string>UIInterfaceOrientationPortrait</string>
  <string>UIInterfaceOrientationLandscapeLeft</string>
  <string>UIInterfaceOrientationLandscapeRight</string>
  <string>UIInterfaceOrientationPortraitUpsideDown</string>
</array>
<key>UISupportedInterfaceOrientations~ipad</key>
<array>
  <string>UIInterfaceOrientationPortrait</string>
  <string>UIInterfaceOrientationLandscapeLeft</string>
  <string>UIInterfaceOrientationPortraitUpsideDown</string>
  <string>UIInterfaceOrientationLandscapeRight</string>
</array>
```

Only using `<preference name="Orientation" value="foo" />`  has an effect on the issue.

When you change the key `UISupportedInterfaceOrientations` to any other string, it will be persisted to the `.plist` correctly.

When you remove the `UISupportedInterfaceOrientations` directives from the *template* `.plist`, the final result is as expected.

### Command or Code

```shell
oliver@oliver-home MINGW64 ~
$ cordova create ios-orientation-bug
$ cd ios-orientation-bug/
$ cordova platform add ios
```
Then add the above `edit-config` directives to the newly created `config.xml` and `cordova prepare`.

### Environment, Platform, Device

Reproduced in builds on OSX and Windows.

### Version information

9.0.0 (cordova-lib@9.0.1)
cordova-ios@5.0.1

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by oliversalzburg** [comment]
It has been noted that there is a possible relation between this issue and:
- https://github.com/apache/cordova-ios/issues/401
- https://github.com/apache/cordova-ios/issues/581

**Comment by raphinesse** [comment]
Thanks for this detailed issue report. I can reproduce the behavior described by you and after some code reading, I unfortunately have to confirm that what you want to do is indeed not possible with `edit-config` or `config-file` tags at the moment. Below I will provide more details on my findings and a possible workaround.

First off, `edit-config` is for editing _attributes_  only. To quote [the docs](https://cordova.apache.org/docs/en/9.x/plugin_ref/spec.html#edit-config) (emphasis mine):

> Instead of appending new children to an XML document tree, `edit-config` makes modifications to _attributes_ of XML elements.

So what you are trying to do above _is not supposed to work_. Deletion of _tags_ is not supported using Cordova's built-in config editing mechanism. Neither for plist nor for any other XML files.

The reason I am making this distinction here, is that plist files are [handled separately from other XML files](https://github.com/apache/cordova-common/blob/2021a39a9eaf473424eafe20e0e126b587933359/src/ConfigChanges/ConfigFile.js#L103). If you look at the linked code, you will realize that the `mode` of the config change is completely disregarded for plist files. In fact, all changes to a plist file are handled by [this code](https://github.com/apache/cordova-common/blob/2021a39a9eaf473424eafe20e0e126b587933359/src/util/plist-helpers.js#L30-L38) which only does _merges_. Either of objects or of arrays. That explains the results you are seeing.

This special treatment of plist files seems to make sense given the fact that, due to their specific structure, we could do very little of use with them if we would apply the default rules for other XML files. However, I could not find this special treatment to be documented anywhere (did I miss it?). Furthermore I clearly see the limitations of the current editing capabilities – for plist files as well as for other XML files.

As a workaround, the following `after_prepare` hook should be able to do what you want:

```js
const fs = require('fs');
const path = require('path');
const plist = require('plist');

module.exports = ({ opts: { projectRoot, platforms } }) => {
    if (!platforms.includes('ios')) return;

    const projectName = 'HelloCordova';
    const platformPath = path.join(projectRoot, 'platforms/ios');
    const infoPlistPath = path.join(platformPath, projectName, `${projectName}-Info.plist`);

    const infoPlist = plist.parse(fs.readFileSync(infoPlistPath, 'utf8'));

    infoPlist.UISupportedInterfaceOrientations = [
        'UIInterfaceOrientationPortrait',
        'UIInterfaceOrientationPortraitUpsideDown',
    ];

    infoPlist['UISupportedInterfaceOrientations~ipad'] = [
        'UIInterfaceOrientationPortrait',
        'UIInterfaceOrientationLandscapeLeft',
        'UIInterfaceOrientationPortraitUpsideDown',
        'UIInterfaceOrientationLandscapeRight',
    ];

    fs.writeFileSync(infoPlistPath, plist.build(infoPlist, { indent: '\t' }));
}
```


So what do we take away from this issue? My suggestions would be:
- The behavior for plist files needs to be documented (if it is indeed not documented yet)
- It would be nice to at least have a warning if using `edit-config`/`mode` with plist files
- We need better config editing capabilities

Any additions?

**Comment by WuglyakBolgoink** [comment]
@raphinesse thank you!

**Comment by oliversalzburg** [comment]
`.build/overwritePlistContent.js`:
```js
#!/usr/bin/env node
const fs    = require( "fs" );
const path  = require( "path" );
const plist = require( "plist" );

const projectName  = "FairManager"
const plistChanges = {
	"UISupportedInterfaceOrientations" : [
		"UIInterfaceOrientationPortrait",
		"UIInterfaceOrientationPortraitUpsideDown"
	],
	"UISupportedInterfaceOrientations~ipad" : [
		"UIInterfaceOrientationPortrait",
		"UIInterfaceOrientationLandscapeLeft",
		"UIInterfaceOrientationPortraitUpsideDown",
		"UIInterfaceOrientationLandscapeRight"
	]
}

module.exports = context => {
	const plistPath = path.resolve( context.opts.projectRoot, "platforms", "ios", projectName, `${projectName}-Info.plist` );

	if( !fs.existsSync( plistPath ) ) {
		console.log( `'${plistPath}' does not exist. Overriding device orientations is skipped.` );
		return;
	}

	const plistContent = plist.parse( fs.readFileSync( plistPath, "utf-8" ) );

	console.log( `Adding desired device orientations to '${plistPath}'...` );
	const plistData = Object.assign( {}, plistContent, plistChanges );
	fs.writeFileSync( plistPath, plist.build( plistData, {
		indent : "\t",
		offset : -1
	} ), "utf-8" );
}
```

In `config.xml`: `<hook src=".build/overwritePlistContent.js" type="after_prepare" />`

**Comment by peitschie** [comment]
Adding to the above, the following snippet can be used inside the context to get the `projectName` dynamically:

```
  const { ConfigParser } = context.requireCordovaModule("cordova-common");
  const appConfig = new ConfigParser(path.resolve(context.opts.projectRoot, "config.xml"));
  const projectName = appConfig.name();
```
