### ISSUE TITLE
Any ideas to supports multiple windows?

### ISSUE THREAD

**Issue by OctHex2016** [apache/cordova-ios#674]
Any ideas to supports multiple windows?
When I click to supports multiple windows, it become black screen. As I know, we need to change to CDVAppDelegate to support UIResponder with UIWindowSceneDelegate, however, I can't make it success. Thanks!

**Comment by dpogue** [comment]
I've thought about this a bit over the past few weeks, and one challenge is that UISceneDelegate is only available in iOS 13, and cordova-ios still needs to support versions as far back as (currently) iOS 10.  It can be done in a conditional way, but that runs the risk of popular plugins being incompatible due to changes in behaviour of methods on the UIAppDelegate vs the UISceneDelegate.

Definitely something we need to examine in more detail as part of the next major version.

**Comment by OctHex2016** [comment]
I just make my app can supports multiple windows. 
But still need to test. Mainly need to add the SceneDelegate and CDVAppDelegate.
