### ISSUE TITLE
 Use of insecure Random Function(s) _random

### ISSUE THREAD

**Issue by jd048** [apache/cordova-ios#739]
# Bug Report

## Problem
The mobile application uses a predictable Random Number Generator (RNG).
Under certain conditions this weakness may expose mobile application data encryption or other
protection based on randomization. For example, if encryption tokens are generated inside of the
application.

### What is expected to happen?
Must use secure random function.

### What does actually happen?
Currently its using insecure random function.

### Environment, Platform, Device

iOS

### Version information

Cordova

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by timbru31** [comment]
Could you link to the exact lines of code, where the function is used?

**Comment by jd048** [comment]
I am not getting line number from vulnerability tool, i am using quixxi.com for vulnerability testing

**Comment by brodybits** [comment]
I think this issue should be considered out of scope since cordova-ios does not offer any form of encryption.

I think a person or a tool should give evidence that an "insecure" random number function is actually used for encryption before flagging this kind of thing as an actual error.

I would highly recommend that you consider look through the code in your plugins to see if you can find a more concrete explanation.

I am also becoming increasingly suspicious of the many third-party scanning tools due to the number of false positives that divert time and attention away from problems that really do need to be solved. See this comment in an SQLite discussion: http://sqlite.1065341.n5.nabble.com/Coding-standard-tc109945.html#a109956

**Comment by breautek** [comment]
Additionally I did a project wide search on the cordova-ios repo for "_random", "random", and "rand" and did not find any results in the native code, and the only usage of random in the js code is for generating callback ids (for plugin native-js communication).

`Math.random()` does indeed fall into the insecure category so I assume the static analysis tool is faulting on this but as @brodybits said, it's not used for encryption or in any security sensitive manner.

**Comment by jcesarmobile** [comment]
Closing the issue.
And please, if scanning tools find security problems in your apps, you have to inspect your app to make sure the problem really comes from cordova, which doesn’t look like it in this case.
