### ISSUE TITLE
[RFC] Improve platform-centered workflow

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-ios#791]
coming from <https://github.com/apache/cordova-ios/pull/769#issuecomment-587411944> (in response to my comment in <https://github.com/apache/cordova-ios/pull/769#pullrequestreview-359914024>):

It looks like there is a Python script (`bin/cordova_plist_to_config_xml`) that is needed to support [platform centered workflow ([1])](https://cordova.apache.org/docs/en/latest/guide/platforms/ios/#platform-centered-workflow), and it would be possible to find a better way to do this. I think it would be ideal if we can find a better, more generic way to do this without need for Python which we know has caused instability between Python 2 and Python 3.

I would like to raise this issue as an enhancement to avoid losing track of something I think we should try to improve at some point (someday).

[1] https://cordova.apache.org/docs/en/latest/guide/platforms/ios/#platform-centered-workflow

**Comment by jcesarmobile** [comment]
The comment says:

> IMO, I think we do not have a lot of resources to focus on the Platform-Center workflow. I think it may have been discussed to consolidate our focus only on the CLI workflow and potentially dropping Platform-Center workflow.

So it says the opposite as you are proposing, he said we should drop the platform-centered workflow and focus only on the CLI, not improve it.

And I think it makes sense since the Platform-Center workflow has been broken on cordova-android from version 4 (~6 years as far as I remember). And even if you are able to make it work on your own, you can't install plugins because it was also broken on the CLI and/or plugman.

Our docs don't work for iOS neither, there are some docs from phonegap team that can be used, but to install the plugins they have to be published as CocoaPods libraries, which they are not. 


So it's not just the tooling, to make it work again it would require an immense amount of work on platforms and plugins too. 

So, it's it worth fixing something that has been broken for years and would need a ton of work to be usable? or is it better to just drop it?
