### ISSUE TITLE
Why does cordova-ios@5.1.1 looses support for iOS 10?

### ISSUE THREAD

**Issue by Adza93** [apache/cordova-ios#799]
Hello everyone!

Just one quick question. I am wondering what is the reason behing bumping mintargetsdk to iOS 11.0 when using cordova-ios@5.1.1? I could not find this information on any other posts, if you know where it is please post a reply.

I could not also find any reference to this on Apache cordova blog post. After adding cordova-ios@5.1.1 I have noticed targetSdk was bumped to iOS 11, tried to lower it to 10, but got exceptions related unknown code for iOS10 codebase related to WkWebView schema handling.

Anyways, does it have something to do with WkWebViewOnly directive and removing UIWeb* directive in pre processing time? There are still number of users using iOS 10, I know there was logic in WkWebViewEngine which differentiated between platform iOS 10 and newer, to initialize main WebView logic, however I am not sure if this needed to be deprecated because of UIWebView depreciation, or something related to xCode 11, or perhaps something related to Apple directly?

Thank you for information :) I am sure everyone in community would like to know this info, to be able to decide if this is the right moment for migration of currently published apps to @5.1.1 :)

**Comment by breautek** [comment]
cordova-ios@5.1.1 does not lose iOS 10 support. 5.1.1 has the `minDeploymentTarget` set to `10.0`.

master does have `minDeploymentTarget` set to `11.0` because the next `cordova-ios` release will be a major release (6.x).

iOS 10 does support `WKWebview` so the wkwebview related changes should not break iOS 10. But I believe scheme handling is only supported in iOS 11+. Apache's wkwebview plugin does not support scheme handling for this reason (but is planned to be added to cordova-ios@6)

Nothing in 5.x should be breaking ios 10, and if something does, please do open a ticket with the bug form filled out, but I suspect it's because your wkwebview plugin implements features only available for iOS11+.

**Comment by Adza93** [comment]
@breautek You are completely right about what you said! Thank you very much.

I have upgraded ordova-plugin-ionic-webview from 2.X to 4.X thinking it wont loose support to iOS 10, however I now see in documentation that latest 4.X release looses support. 

I hope that current latest 2.5.3 version implements support WK_WEB_VIEW_ONLY, so I can eliminate ITMS depreciation warnings. I do not see this directive in this plugin code, however cant find UIWebView references in plugin.Do you maybe know something about this also?

Thanks again! :)

**Comment by breautek** [comment]
I'm not really familiar with ionic, I'd suggest asking in Ionic's slack.
