### ISSUE TITLE
ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by jagovea** [apache/cordova-ios#831]
hi i am having trouble compiling my app i am getting ios error ITMS-90809: Deprecated API Usage.

This is my simple XML:
```
<? xml version = "1.0" encoding = "UTF-8"?>
<widget xmlns = "http://www.w3.org/ns/widgets"
        xmlns: gap = "http://phonegap.com/ns/1.0"
        id = "com.test"
        versionCode = "0.12.48"
        version = "0.12.48">
<engines>
<engine name = "cordova-ios" version = "> = 5.1.1" />
    </engines>

<allow-navigation href = "*" />
<name> test </name>
<description> test </description>
<author href = "https://www.test.com" email = "text@test.com"> TEST </author>
<platform name = "ios">
<preference name = "WKWebViewOnly" value = "true" />
<feature name = "CDVWKWebViewEngine">
<param name = "ios-package" value = "CDVWKWebViewEngine" />
</feature>
<preference name = "CordovaWebViewEngine" value = "CDVWKWebViewEngine" />
    </platform>
<plugin name = "cordova-plugin-wkwebview-engine" spec = "1.2.1" />
</widget>

```
Can someone please help me, a thousand thanks.

**Comment by breautek** [comment]
ITMS-90809 is the deprecation notice for the `UIWebView`. It means something in your codebase is still referencing the `UIWebView`.

Cordova's codebase will exclude references to `UIWebView` if you use the [WKWebViewOnly](https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html) flag, while using cordova-ios@5.1.1. It appears this is what you're already using.

The only thing we can suggest is to determine if your plugins also needs updating. The latest version of the `inappbrowser` for example will also respect the `WKWebViewOnly` flag. Other third-party plugins may also reference `UIWebView` and the maintainers of those plugins will need to update their plugins.

__This is obviously only speculation because you didn't fill out the issue form__

This is the best answer we can give with the details provided. If you think you've found a bug, please open a new issue and fill out the issue form completely. If you still need further assistance, you can search through our [slack](http://slack.cordova.io/) channels or ask for support there.

**Comment by breautek** [comment]
One additional note... if you're still using phonegap build (I see the phonegap namespace...), I believe they are locked to an older version of cordova-ios which does not support the `WKWebViewOnly` flag. And apparently they are in maintenance mode, so you may not see an update in a timely fashion. 

See https://community.adobe.com/t5/phonegap/cordova-ios-5-1-1-is-out-when-will-phonegap-build-cli-be-updated/td-p/10775190?page=1 for more information.

**Comment by jagovea** [comment]
First of all, thank you very much for your prompt response. I am new to the subject, I am using Monaca.

The only thing I add to the XML is the information I posted and it keeps showing me the errors. Can you help me? Thanks a lot.

**Comment by jagovea** [comment]
additional, these are the plugins that I have active for now.

![Captura de Pantalla 2020-05-04 a la(s) 19 19 14](https://user-images.githubusercontent.com/40873512/81025427-3fee8680-8e3c-11ea-86c4-38f7c3a71345.png)

**Comment by breautek** [comment]
I'm not familiar with monaca, but it says you're using cordova-ios@5.0.1 which is incorrect. It needs to be version 5.1.1.

5.0.1 doesn't have the wkwebviewonly flag.

I'd advise you to contact monaca support channels to learn how to get that upgraded to 5.1.1.
