### ISSUE TITLE
ITMS-90809 error and app rejection with ios-5.1.1 and all updated plugins.

### ISSUE THREAD

**Issue by hamid-hassani** [apache/cordova-ios#854]
Hi,
I am still get ITMS-90809 error and rejection by apple for using UIWebView using. However I do not use any of that.

All plugins are updated:
<pre>
card.io.cordova.mobilesdk 2.1.0 "CardIO"
com-badrit-base64 0.2.0 "Base64"
com.paypal.cordova.mobilesdk 3.5.0 "PayPalMobile"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ios-camera-permissions 1.2.0 "iOS Permissions"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-wkwebview-engine 1.2.1 "Cordova WKWebView Engine"
es6-promise-plugin 4.2.2 "Promise"
onesignal-cordova-plugin 2.9.1 "OneSignal Push Notifications"
</pre>

<strong>I am using latest ios-cordova:</strong>
<pre>
@ionic/cli-utils  : 1.19.1
 ionic (Ionic CLI) : 3.19.1
 cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1) 
 @ionic/app-scripts : 3.1.9
 Cordova Platforms  : ios 5.1.1
Ionic Framework    : ionic-angular 3.9.2
</pre>

And using proper flags in config.xml and set "WKWebViewOnly" to true.
I followed this <a href="https://www.npmjs.com/package/cordova-plugin-wkwebview-engine">link</a>

Searching "uiwebview" in Xcode only returns matched folder of:
<pre>
<strong>CDVUIWebViewEngine</strong>
<strong>CDVUIWebViewNavigationDelegate....</strong>
<strong>CDVUIWebViewDelegate</strong>
</pre>

Is there any help? <strong>I read all other related topic </strong>,still no chance.

<Strong>Can it comes from latest version of PayPalMobile?</strong>

**Comment by breautek** [comment]
> Can it comes from latest version of PayPalMobile?

I don't know about that plugin specifically, but yes plugins could be referencing `UIWebView` and the maintainers needs to update their plugin to use `WKWebView` if they haven't already done so.

> Searching "uiwebview" in Xcode only returns matched folder of:

Do note that when it comes to Apache's maintained code bases, the references will still be in the source code, but they are wrapped around a compiler flag so these references are omitted in the bundled binary.

**Comment by hamid-hassani** [comment]
So how we can track WKWebView usage?

**Comment by breautek** [comment]
Not sure how to do it efficiently. I know several people just remove plugins and do a test upload to the itunes connect to see if they get an email, but I understand that this isn't really an ideal way of determining if your app is WKWebView compliant.

Also their plugins are deprecated because the PayPal sdk is deprecated. This doesn't proof that the paypal plugin or its SDKs are using `UIWebView` but if they were using it, then chances are they haven't refactored, since the notice was added 16 months ago. Their deprecation notice states:

> Important: PayPal Mobile SDKs are Deprecated. The APIs powering them will remain operational long enough for merchants to migrate, but the SDKs themselves will no longer be updated. Please use Braintree Direct in supported countries. In other countries, use Express Checkout and choose the Braintree SDK integration option.

I also notice they include pre-compiled library files, so it is possible they are referencing `UIWebView` but aren't finding in xcode because the references are packed inside these binaries.

**Comment by hamid-hassani** [comment]
I confirm "PayPal" cause this problem. When you use latest version of PayPal cordova plugin, it sill happens, removing that, solve problem!

@ cordova please update this problem, closing this issue, do not help other people to solve their problem.

Still there is no any PayPal integration for IONIC 3 except Brain Tree, However, you need to do backend.

Please update Cordova PayPpal information, no one can use this plugin anymore.

**Comment by breautek** [comment]
Glad you identified the problem, but this is not a plugin is owned by PayPal, not Cordova so there is nothing Cordova can do.

Also the solution to this problem is going to be domain specific. PayPal offers two different paths depending on your situation, it's going to be up to you to research both paths and determine what will work best for you.

**Comment by DuaneQ** [comment]
@hamid-hassani did you resolve this yet?

I have the same issue and I noticed in my project I also have these 3 references but I do not have a payPal plugin so I'm not sure which plugin is using it or how to do away with them.
CDVUIWebViewEngine
CDVUIWebViewNavigationDelegate....
CDVUIWebViewDelegate


See my stack post.  I'm still stuck
https://stackoverflow.com/questions/67097946/removed-uiwebview-from-ionic-project-but-still-getting-rejected-by-the-app-store
