### ISSUE TITLE
BackupWebStorage on iOS - set to none, but data still persists after deleting app from device

### ISSUE THREAD

**Issue by bengrah-miller** [apache/cordova-ios#908]
We're developing an app using Ionic/Cordova that saves items to using the SecureStorage plugin. Items are saving fine, but when we uninstall the app reinstall, the items we've saved before are still there. We would like to stop this behaviour.

We found out about the BackupWebStorage property (link) and have set this to none, however the data still persists despite this being set.

Is there anything else we can check, turn off, set in Xcode that we have to do at this point to get this to work?

Thank you, bengrah

**Comment by timbru31** [comment]
IIRC that’s stock iOS behavior: keep old app data for some time, if the user decides to reinstall the app, his data is still there. I have no official documentation links right now though.

**Comment by bengrah-miller** [comment]
@timbru31 Is that not what the `BackupWebStorage` property is meant to prevent?

**Comment by jcesarmobile** [comment]
web storage is local storage, session storage, web sql and some possible webview storages.

Secure storage plugin saves to the keychain, which can persist after app uninstalls, report the issue in the secure storage plugin repo, there are a few workarounds they could add to the plugin to delete/reset existing data on first launch after reinstall. But it's not possible to delete on uninstall because there is no uninstall event or notification the app can hook to.
