### ISSUE TITLE
(DeviceMotion) requestPermission set a WKUIDelegate with cordova-ios@6.0.0

### ISSUE THREAD

**Issue by Dirk-27** [apache/cordova-ios#914]
## Problem

Here https://github.com/Dirk-27/cordova-requestPermission-issue is an example that illustrates the issue. 

With cordova-ios@6.0.0 we need to request for permission to access deviceMotionEvent. This results in the following dialog being displayed.

![IMG_C810EC9221E4-1](https://user-images.githubusercontent.com/45331389/85283414-a03d9400-b48d-11ea-9cbc-a9a4ca9d9e58.jpeg)

this also causes apple to reject the app. See #891

### What is expected to happen?
Like with cordova-ios@5.1.1. It should be possible to get DeviceMotions without displaying a native dialog since this https://bugs.webkit.org/show_bug.cgi?id=203287 is already fixed.

see https://github.com/Dirk-27/cordova-requestPermission-issue/tree/cordova-ios-5.1.1.

### What does actually happen?
A native dialog is displayed which ask for permission to the user. see https://github.com/Dirk-27/cordova-requestPermission-issue

### Command or Code

Use following commands to build the example https://github.com/Dirk-27/cordova-requestPermission-issue
- `cordova prepare`
- `cordova build ios`

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Since this is a bug within wkwebview, there is going to be very little Cordova can do about this issue. All we can really do is wait until their fix lands in a production release of iOS.

In my apps, I still use the old & deprecated [cordova-plugin-device-motion](https://github.com/apache/cordova-plugin-device-motion), and I haven't seen this issue arise for me on wkwebview, so this may be a workaround for the time being. More specifically, I believe my apps use 1.x version of that plugin. My apps however isn't on cordova-ios@6 yet, but I don't think that is significant here.

Related: https://github.com/apache/cordova-plugin-device-motion/issues/69

**Comment by Dirk-27** [comment]
I I'm not sure if it's the wkwebview. I tried it with this app https://apps.apple.com/us/app/webview-wkwebview-and-uiwebview-rendering/id928647773. It should also use the wkwebview and I could not see the issue.

Thanks for the solution but unfortunately it's not a considerable solution for us since we use aframe.io and do not directly access the motions data.

**Comment by jcesarmobile** [comment]
As of iOS 13.6 it still prompts the user, it's not clear to me that the app is not supposed to prompt in WKWebView.
I've reported 3 issues I've find in the prompt like not showing the app name, not showing the usage description and not remembering the answer.
https://bugs.webkit.org/show_bug.cgi?id=213467
https://bugs.webkit.org/show_bug.cgi?id=213468
https://bugs.webkit.org/show_bug.cgi?id=213469

There is nothing we can do about it as they are WKWebView, so I'm closing this issue.
