### ISSUE TITLE
cordova-ios@6.1.0 Not installed

### ISSUE THREAD

**Issue by UTSOURCE** [apache/cordova-ios#917]
![QQ截图20200624150314](https://user-images.githubusercontent.com/14830459/85511904-e597c800-b62b-11ea-85d1-2ff55a0f6bc3.png)
cordova-ios@6.1.0 Not installed

**Comment by erisu** [comment]
Not released.

**Comment by UTSOURCE** [comment]
@erisu Can I install version 6.0.0 or higher?
For example, the beta version that is updated every day, how can I install it if I can?

**Comment by erisu** [comment]
If you are talking about our nightly builds, you can install it like this:

```bash
cordova platform add ios@nightly
```

But nightly builds have not been officially voted for release and is not recommended to be used in production environment. Nightly builds may contain bugs.

Using nightly is only recommended for testing upcoming releases and so that you could discover and report issues back to us.

You could also install the `6.1.0` tag from GitHub but again this tag `6.1.0` is not the official release.

```bash
cordova platform add github:apache/cordova-ios#6.1.0
```

An official release tag would be `rel/6.1.0` but is not yet created but typically once that tag is created, it will be uploaded to the npm registry as well.

**Comment by UTSOURCE** [comment]
@erisu Thank you
